//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.RecipeProcesses = new HashSet<RecipeProcess>();
        }
    
        public int IngredientId { get; set; }
        public int RecipeId { get; set; }
        public int FoodId { get; set; }
        public int Quantity { get; set; }
        public int UnitId { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeProcess> RecipeProcesses { get; set; }
    }
}
