//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeProcess
    {
        public int RecipeId { get; set; }
        public int StepNumber { get; set; }
        public Nullable<int> RelatedStep { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public string SpecialInstructions { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
